const Snowball = require("../dist/Snowball");

const testData = {
  danish: [
    ["spiller", "spil"], ["spillede", "spilled"], ["løber", "løb"],
    ["spil", "spil"], ["begyndelse", "begynd"], ["begynd", "begynd"],
    ["handlinger", "handling"], ["handling", "handling"], ["handler", "handl"],
    ["forandring", "forandring"], ["forandringer", "forandring"], ["forandret", "forandr"],
    ["industri", "industri"], ["industriens", "industri"], ["industrier", "industri"],
    ["bedre", "bedr"], ["bedst", "bedst"], ["bedste", "bedst"],
    ["begynder", "begynd"], ["løb", "løb"],
  ],
  dutch: [
    ["speelde", "speeld"], ["speelt", "speelt"], ["spel", "spel"],
    ["lopen", "lop"], ["loopt", "loopt"], ["liep", "liep"],
    ["bedrijf", "bedrijf"], ["bedrijven", "bedrijv"], ["bedrijfs", "bedrijf"],
    ["verandering", "verander"], ["veranderingen", "verander"], ["veranderd", "veranderd"],
    ["mogelijkheid", "mogelijk"], ["mogelijkheden", "mogelijk"], ["mogelijk", "mogelijk"],
    ["gebeuren", "gebeur"], ["gebeurd", "gebeurd"], ["gebeurt", "gebeurt"],
    ["aankomst", "aankomst"], ["aankomsten", "aankomst"], ["aankomend", "aankom"],
  ],
  english: [
    ["plays", "play"], ["playing", "play"], ["played", "play"],
    ["runs", "run"], ["running", "run"], ["ran", "ran"],
    ["connections", "connect"], ["connection", "connect"], ["connect", "connect"],
    ["generous", "generous"], ["generously", "generous"], ["generosity", "generos"],
    ["cats", "cat"], ["cat", "cat"], ["processing", "process"],
    ["process", "process"], ["processed", "process"], ["processes", "process"],
    ["runner", "runner"], ["hopping", "hop"], ["hopped", "hop"],
    ["sing", "sing"], ["singing", "sing"], ["sings", "sing"], ["singer", "singer"],
  ],
  finnish: [
    ["puheenjohtaja", "puheenjohtaj"], ["kansanedustaja", "kansanedustaj"],
    ["kansanedustajien", "kansanedustaj"], ["yhteiskunta", "yhteiskun"],
    ["yhteiskunnan", "yhteiskun"], ["toiminta", "toimin"], ["toiminnan", "toimin"],
    ["merkittävä", "merkittäv"], ["merkittävän", "merkittäv"],
    ["tekeminen", "tekemin"], ["tekemisen", "tekemis"],
    ["saaminen", "saamin"], ["saamisen", "saamis"],
    ["meneminen", "menemin"], ["menemisen", "menemis"],
    ["tuleminen", "tulemin"], ["tulemisen", "tulemis"],
    ["olemisen", "olemis"], ["olemista", "olem"],
    ["puheenjohtajan", "puheenjohtaj"],
  ],
  french: [
    ["joue", "jou"], ["jouer", "jou"], ["jouant", "jou"], ["joué", "jou"],
    ["changeant", "chang"], ["changé", "chang"], ["change", "chang"], ["changés", "chang"],
    ["connexion", "connexion"], ["connecter", "connect"], ["connecté", "connect"],
    ["gouvernement", "gouvern"], ["gouvernements", "gouvern"],
    ["application", "appliqu"], ["applications", "appliqu"],
    ["technologique", "technolog"], ["technologiques", "technolog"],
    ["technologie", "technolog"], ["technologies", "technolog"],
    ["traitement", "trait"], ["traiter", "trait"], ["traité", "trait"],
  ],
  german: [
    ["spielen", "spiel"], ["spielte", "spielt"], ["spielend", "spielend"],
    ["Veränderung", "Verander"], ["Veränderungen", "Verander"],
    ["Wissenschaft", "Wissenschaft"], ["Wissenschaftler", "Wissenschaftl"],
    ["Unternehmen", "unternehm"], ["Möglichkeit", "Moglich"], ["Möglichkeiten", "Moglich"],
    ["Verantwortung", "Verantwort"], ["Arbeit", "Arbeit"], ["Arbeiter", "Arbeit"],
    ["Arbeiten", "Arbeit"], ["arbeitend", "arbeit"], ["Arbeits", "Arbeit"],
    ["groß", "gross"], ["große", "gross"], ["größte", "grosst"],
    ["unternehmen", "unternehm"],
  ],
  hungarian: [
    ["játszik", "játsz"], ["játszott", "játszot"], ["játék", "játe"],
    ["játékos", "játékos"], ["változás", "változás"], ["változások", "változás"],
    ["változat", "változ"], ["lehetőség", "lehetőség"], ["lehetőségek", "lehetőség"],
    ["fejlesztés", "fejlesztés"], ["fejlesztések", "fejlesztés"],
    ["kapcsolat", "kapcsol"], ["kapcsolatok", "kapcsolat"],
    ["tevékenység", "tevékenység"], ["tevékenységek", "tevékenység"],
    ["munka", "mun"], ["munkás", "munkás"], ["munkálat", "munkál"],
    ["nagy", "nagy"], ["nagyobb", "nagyobb"], ["legnagyobb", "legnagyobb"],
  ],
  indonesian: [
    ["berlari", "lari"], ["berjalan", "jalan"], ["perubahan", "ubah"],
    ["kegiatan", "giat"], ["pembelajaran", "ajar"], ["pengembangan", "embang"],
    ["masyarakat", "masyarakat"], ["menulis", "tulis"], ["membaca", "baca"],
    ["pendidikan", "didik"], ["kesehatan", "sehat"], ["pertanian", "tani"],
    ["perkembangan", "kembang"], ["pembangunan", "bangun"], ["penggunaan", "guna"],
    ["pelajaran", "ajar"], ["keindahan", "indah"], ["kemajuan", "maju"],
    ["pengetahuan", "tahu"], ["pengertian", "erti"],
  ],
  italian: [
    ["gioca", "gioc"], ["giocare", "gioc"], ["giocando", "gioc"], ["giocato", "gioc"],
    ["cambiamento", "camb"], ["applicazione", "applic"], ["applicazioni", "applic"],
    ["tecnologica", "tecnolog"], ["tecnologiche", "tecnolog"],
    ["informazione", "inform"], ["informazioni", "inform"],
    ["sviluppo", "svilupp"], ["sviluppare", "svilupp"], ["sviluppato", "svilupp"],
    ["elaborazione", "elabor"], ["elaborare", "elabor"], ["elaborato", "elabor"],
    ["grande", "grand"], ["grandi", "grand"], ["massimo", "massim"],
  ],
  norwegian: [
    ["spiller", "spill"], ["spilte", "spilt"], ["spill", "spill"],
    ["løper", "løp"], ["løp", "løp"], ["begynnelse", "begynn"],
    ["begynn", "begynn"], ["begynner", "begynn"], ["handlinger", "handling"],
    ["handling", "handling"], ["handler", "handl"], ["forandring", "forandring"],
    ["forandringer", "forandring"], ["forandret", "forandr"],
    ["utvikling", "utvikling"], ["utviklingen", "utvikling"], ["utvikle", "utvikl"],
    ["bedre", "bedr"], ["best", "best"], ["beste", "best"],
  ],
  portuguese: [
    ["joga", "jog"], ["jogar", "jog"], ["jogando", "jog"], ["jogado", "jog"],
    ["mudança", "mudanc"], ["mudanças", "mudanc"],
    ["aplicação", "aplic"], ["aplicações", "aplic"],
    ["tecnológica", "tecnológ"], ["tecnológicas", "tecnológ"],
    ["desenvolvimento", "desenvolv"], ["desenvolver", "desenvolv"], ["desenvolvido", "desenvolv"],
    ["informação", "inform"], ["informações", "inform"],
    ["processamento", "process"], ["processar", "process"], ["processado", "process"],
    ["grande", "grand"], ["grandes", "grand"], ["máximo", "máxim"],
  ],
  romanian: [
    ["joacă", "joac"], ["jucat", "jucat"], ["jucând", "jucând"],
    ["schimbare", "schimb"], ["schimbări", "schimbăr"],
    ["dezvoltare", "dezvolt"], ["aplicație", "aplicaț"], ["aplicații", "aplicaț"],
    ["informație", "informaț"], ["informații", "informaț"],
    ["tehnologie", "tehnolog"], ["tehnologii", "tehnolog"],
    ["procesare", "proces"], ["procesa", "proces"], ["procesat", "proces"],
    ["mare", "mar"], ["mari", "mar"], ["maxim", "max"],
    ["schimbări", "schimbăr"], ["dezvoltare", "dezvolt"],
  ],
  russian: [
    ["играет", "игра"], ["играть", "игра"], ["изменение", "изменен"],
    ["изменения", "изменен"], ["развитие", "развит"], ["развития", "развит"],
    ["применение", "применен"], ["применения", "применен"],
    ["информация", "информац"], ["информации", "информац"],
    ["технология", "технолог"], ["технологии", "технолог"],
    ["обработка", "обработк"], ["обработки", "обработк"],
    ["большой", "больш"], ["большая", "больш"], ["большое", "больш"],
    ["максимум", "максимум"], ["максимальный", "максимальн"],
    ["игра", "игр"],
  ],
  spanish: [
    ["juega", "jueg"], ["jugar", "jug"], ["jugando", "jug"], ["jugado", "jug"],
    ["cambio", "cambi"], ["cambios", "cambi"],
    ["aplicación", "aplic"], ["aplicaciones", "aplic"],
    ["tecnológica", "tecnolog"], ["tecnológicas", "tecnolog"],
    ["desarrollo", "desarroll"], ["desarrollar", "desarroll"], ["desarrollado", "desarroll"],
    ["información", "inform"], ["informaciones", "inform"],
    ["procesamiento", "proces"], ["procesar", "proces"], ["procesado", "proces"],
    ["grande", "grand"], ["grandes", "grand"], ["máximo", "maxim"],
  ],
  swedish: [
    ["spelar", "spel"], ["spelade", "spel"], ["spel", "spel"],
    ["löper", "löp"], ["löpare", "löp"],
    ["förändring", "förändring"], ["förändringar", "förändring"], ["förändrad", "förändr"],
    ["utveckling", "utveckling"], ["utvecklingen", "utveckling"], ["utveckla", "utveckl"],
    ["tillämpning", "tillämpning"], ["tillämpningar", "tillämpning"],
    ["information", "information"], ["teknik", "teknik"], ["tekniker", "teknik"],
    ["stor", "stor"], ["större", "störr"], ["störst", "störst"],
    ["förändring", "förändring"],
  ],
  turkish: [
    ["oynar", "oynar"], ["oynamak", "oynamak"], ["oynanan", "oynana"],
    ["değişiklik", "değişiklik"], ["değişiklikler", "değişiklik"],
    ["geliştirme", "geliştirme"], ["geliştirmek", "geliştirmek"],
    ["uygulama", "uygula"], ["uygulamalar", "uygulama"],
    ["bilgi", "bilgi"], ["bilgiler", "bilgi"],
    ["teknoloji", "teknoloj"], ["teknolojiler", "teknoloji"],
    ["işlem", "işle"], ["işleme", "işle"], ["büyük", "büyük"],
    ["değişiklik", "değişiklik"], ["bilgi", "bilgi"],
  ],
};

describe("Stemming accuracy", () => {
  for (const [language, cases] of Object.entries(testData)) {
    describe(language, () => {
      it.each(cases)("stems '%s' => '%s'", (input, expected) => {
        const stemmer = Snowball(language);
        stemmer.setCurrent(input);
        stemmer.stem();
        expect(stemmer.getCurrent()).toBe(expected);
      });
    });
  }
});
